[package]
name = "socket_utils"
version = "0.1.0"
edition = "2018"

[dependencies]
bip_utils = { path= "../bip_utils"}
framework_constants = { path= "../framework_constants"}
log = "0.4.8"
spsc-bip-buffer = "0.2.1"
error-chain = "0.12.1"